// Cross-language golden tests: DetectorKit must reproduce the Python
// detector's outputs exactly. Fixtures live at repo-root fixtures/ and are
// generated by tools/gen_golden.py (the Python detector is the oracle).

import Foundation
import XCTest
@testable import DetectorKit

private func repoRoot() -> URL {
    // .../macapp/FillerKillerKit/Tests/DetectorKitTests/GoldenTests.swift -> repo root
    URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent() // GoldenTests.swift
        .deletingLastPathComponent() // DetectorKitTests
        .deletingLastPathComponent() // Tests
        .deletingLastPathComponent() // FillerKillerKit
        .deletingLastPathComponent() // macapp
}

private func loadJSON<T: Decodable>(_ type: T.Type, _ relativePath: String) throws -> T {
    let url = repoRoot().appendingPathComponent(relativePath)
    let data = try Data(contentsOf: url)
    let decoder = JSONDecoder()
    decoder.keyDecodingStrategy = .convertFromSnakeCase
    return try decoder.decode(type, from: data)
}

// MARK: - Detector golden

private struct Golden: Decodable {
    let spanSemantics: String
    let textCases: [TextCase]
    let utteranceCases: [UtteranceCase]
}

private struct TextCase: Decodable {
    let name: String
    let text: String
    let includeVocalized: Bool
    let expectedHits: [ExpectedHit]
}

private struct ExpectedHit: Decodable, Equatable {
    let term: String
    let category: String
    let start: Int
    let end: Int
}

private struct UtteranceCase: Decodable {
    let name: String
    let utterances: [ExpectedUtterance]
    let speaker: String
    let includeVocalized: Bool
    let expected: ExpectedResult
}

private struct ExpectedUtterance: Decodable, Equatable {
    let speaker: String
    let text: String
}

private struct ExpectedResult: Decodable {
    let wordCount: Int
    let fillerCount: Int
    let per100Words: Double
    let hits: [ExpectedIndexedHit]
}

private struct ExpectedIndexedHit: Decodable, Equatable {
    let term: String
    let category: String
    let start: Int
    let end: Int
    let utteranceIdx: Int
}

final class DetectorGoldenTests: XCTestCase {
    func testSpanSemantics() throws {
        let golden = try loadJSON(Golden.self, "fixtures/detector/golden.json")
        XCTAssertEqual(golden.spanSemantics, "unicode_code_points")
    }

    func testTextCases() throws {
        let golden = try loadJSON(Golden.self, "fixtures/detector/golden.json")
        XCTAssertFalse(golden.textCases.isEmpty)
        for c in golden.textCases {
            let hits = analyzeText(c.text, includeVocalized: c.includeVocalized)
            let got = hits.map {
                ExpectedHit(term: $0.term, category: $0.category, start: $0.start, end: $0.end)
            }
            XCTAssertEqual(got, c.expectedHits, "text case '\(c.name)' diverged from Python oracle")
        }
    }

    func testUtteranceCases() throws {
        let golden = try loadJSON(Golden.self, "fixtures/detector/golden.json")
        XCTAssertFalse(golden.utteranceCases.isEmpty)
        for c in golden.utteranceCases {
            let result = analyzeUtterances(
                c.utterances.map { Utterance(speaker: $0.speaker, text: $0.text) },
                speaker: c.speaker,
                includeVocalized: c.includeVocalized
            )
            XCTAssertEqual(result.wordCount, c.expected.wordCount, "word_count in '\(c.name)'")
            XCTAssertEqual(result.fillerCount, c.expected.fillerCount, "filler_count in '\(c.name)'")
            XCTAssertEqual(result.per100Words, c.expected.per100Words,
                           accuracy: 0.0, "per_100_words in '\(c.name)'")
            let got = result.hits.map {
                ExpectedIndexedHit(term: $0.term, category: $0.category,
                                   start: $0.start, end: $0.end, utteranceIdx: $0.utteranceIdx)
            }
            XCTAssertEqual(got, c.expected.hits, "hits in '\(c.name)'")
        }
    }
}

// MARK: - Segment-merge golden

private struct MergeGolden: Decodable {
    let cases: [MergeCase]
}

private struct MergeCase: Decodable {
    let name: String
    let segments: [MaybeSegment]
    let expected: [ExpectedUtterance]
}

final class MergeGoldenTests: XCTestCase {
    func testMergeCases() throws {
        let golden = try loadJSON(MergeGolden.self, "fixtures/granola/merge.json")
        XCTAssertFalse(golden.cases.isEmpty)
        for c in golden.cases {
            let merged = mergeSegments(c.segments)
            let got = merged.map { ExpectedUtterance(speaker: $0.speaker, text: $0.text) }
            XCTAssertEqual(got, c.expected, "merge case '\(c.name)' diverged from Python oracle")
        }
    }
}
